import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/Navbar'

// export default function Home() {
//   return (
//     <div>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <Navbar/>
//       {/* <Main/> */}
//     </div>
//   )
// }

import React from "react";
import Nav from './components/Nav';
import requests from '../utils/requests';
// import requests from "../utils/requests";

const Home = ({results}) => {
  // console.log(results);

  return (
    <>
    <Navbar/>
    <Nav/>
    {/* Bannner................. */}
 <section class="container mx-auto p-10 md:py-20 px-0 md:p-10 md:px-0">
        <section class="p-5 md:p-0  2xl:grid-cols-4 gap-10">
         


            

        


        <article
  className="p-10 h-96  w-full rounded-xl text-gray-100 xl:col-span-2 bg-center bg-cover transform duration-500 hover:-translate-y-1 cursor-pointer"
  style={{
    backgroundImage:
      "url(https://netflixjunkie.com/wp-content/uploads/2021/11/Netflix-Background-1.jpg)"
  }}
>


  <div className="mt-16 flex justify-between ">
    <span className="p-3 pl-0 font-bold">Travel Guide</span>
    <span className="p-3 px-5 bg-gray-200  rounded-md text-base hover:bg-orange-600 cursor-pointer hover:text-white text-black ">
      Paid Membership
    </span>
  </div>
</article>
         
        </section>
    </section>


{/* Movie posts................. */}
<h1 className=' text-4xl font-bold text-center text-red-600'>Our Collection</h1>
<div class="px-4 py-16 mx-auto sm:max-w-xl md:max-w-full lg:max-w-screen-xl md:px-24 lg:px-8 lg:py-20">
  <div class="grid gap-5 lg:grid-cols-3 sm:max-w-sm sm:mx-auto lg:max-w-full">
  {results.results.map((e)=>{
 return <div class="overflow-hidden transition-shadow duration-300 bg-white rounded">
 <a href="/" aria-label="Article"><img src={`http://image.tmdb.org/t/p/w500/${e.backdrop_path}`} alt="" /></a>
 <div class="py-5">
   <p class="mb-2 text-xs font-semibold text-gray-600 uppercase">

     {e.release_date}
   </p>
   <a href="/" aria-label="Article" class="inline-block mb-3 text-black transition-colors duration-200 hover:text-deep-purple-accent-700"><p class="text-2xl font-bold leading-5">   {e.title || e.original_name}</p></a>
   <p class="mb-4 text-gray-700">
   {e.overview}
   </p>
   <div class="flex space-x-4">
     <a href="/" aria-label="Likes" class="flex items-start text-gray-800 transition-colors duration-200 hover:text-deep-purple-accent-700 group">
       <div class="mr-2">
         <svg
           xmlns="http://www.w3.org/2000/svg"
           width="24"
           height="24"
           viewBox="0 0 24 24"
           stroke="currentColor"
           stroke-linecap="round"
           stroke-linejoin="round"
           stroke-width="2"
           class="w-5 h-5 text-gray-600 transition-colors duration-200 group-hover:text-deep-purple-accent-700"
         >
           <polyline points="6 23 1 23 1 12 6 12" fill="none" stroke-miterlimit="10"></polyline>
           <path d="M6,12,9,1H9a3,3,0,0,1,3,3v6h7.5a3,3,0,0,1,2.965,3.456l-1.077,7A3,3,0,0,1,18.426,23H6Z" fill="none" stroke="currentColor" stroke-miterlimit="10"></path>
         </svg>
       </div>
       <p class="font-semibold">{e.popularity}</p>
     </a>
     <a href="/" aria-label="Comments" class="flex items-start text-gray-800 transition-colors duration-200 hover:text-deep-purple-accent-700 group">
       <div class="mr-2">
         <svg
           xmlns="http://www.w3.org/2000/svg"
           width="24"
           height="24"
           viewBox="0 0 24 24"
           stroke-linecap="round"
           stroke-linejoin="round"
           stroke-width="2"
           stroke="currentColor"
           class="w-5 h-5 text-gray-600 transition-colors duration-200 group-hover:text-deep-purple-accent-700"
         >
           <polyline points="23 5 23 18 19 18 19 22 13 18 12 18" fill="none" stroke-miterlimit="10"></polyline>
           <polygon points="19 2 1 2 1 14 5 14 5 19 12 14 19 14 19 2" fill="none" stroke="currentColor" stroke-miterlimit="10"></polygon>
         </svg>
       </div>
       <p class="font-semibold">81</p>
     </a>
   </div>
 </div>
</div>}
  )}
  </div>
</div>
    </>
  );
};


export async function getServerSideProps(context) {
  const genre =  context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`);
  const results = await request.json();
  return {
    props: {results}, // will be passed to the page component as props
  }
}


export default Home;



